### ISSUE TITLE
Bundled version of JSI PartUtilities is outdated

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [linuxgurugamer/VesselViewer#15]
VesselViewer v0.8.8.2 shipped with PartUtilities v0.4.2.1, not v0.5.0.4.

**Comment by linuxgurugamer** [comment]
nuts

**Comment by linuxgurugamer** [comment]
Actually, I am pretty sure it is the correct version, just a bad .version file.
i will get it fixed with a new release

**Comment by linuxgurugamer** [comment]
Thanks
