### ISSUE TITLE
VVRPM package clashes with current RPM

### ISSUE THREAD

**Issue by mathuin** [linuxgurugamer/VesselViewer#7]
I recently reported an issue to the RPM guys (autopilot control not present) but upon extensive reproduction with just RPM, MJ, and MM installed found that the problem went away.  I added mods back by hand and learned that VVRPM appears to include its own version of RPM.  When I unzipped by hand and said 'No' to all the files that RPM had already installed, the issue went away.

Is there a particular reason that RPM (or at least parts of it) is included in VVRPM?  Would it be possible to package VV with the RPM plugin and have it ignored if RPM isn't installed?  On the bright side, that would reduce the number of packages for release day by one -- two, if you can do the same for the toolbar. :-)

**Comment by linuxgurugamer** [comment]
How are you installing it?

**Comment by mathuin** [comment]
Previously, I installed via CKAN.  This time, I downloaded the VVRPM zip file from the releases page as mentioned above.  Effectively, `unzip ~/Downloads/VesselView-RPM-0.8.6.zip -d ~/.steam/steamapps/common/Kerbal\ Space\ Program/` but selecting 'no don't replace files' when asked.

Is there anything that you're adding to the `GameData/JSI` directory that *isn't* part of stock RPM?

**Comment by mathuin** [comment]
Holy crap, just checked out the repo and realized that it includes the source to RPM v0.29.1 and Toolbar 1.7.15.0 inside!  The build process is clearly Linux-friendly but somewhat explicit in its default values.

I am no C# programmer, but I have poked about a few other addons.  Would you be interested in a pull request that refactors the code and build process?  I would be happy to do it.  The end result would be a single deliverable which would check for RPM and Toolbar already installed before trying to use that functionality.  My template would be from https://github.com/AndyMt/GravityTurn, which is a project to which I have made small related contributions and which has conditionally-enabled functionality depending on whether MechJeb is installed.
