### ISSUE TITLE
VesselViewer Tab in RPM does not display anything and crashes the given console

### ISSUE THREAD

**Issue by MeadeRobert** [linuxgurugamer/VesselViewer#9]

**Comment by linuxgurugamer** [comment]
Totally useless report.

At least give me a log file, or something to know what you are doing.

**Comment by MeadeRobert** [comment]
I just used 0.8.6 instead and that works fine. Where would I find this log given that there was no actual crash just that RPM wasn't displaying anything and then I couldn't switch to a different display.

**Comment by danpolanco** [comment]
@MeadeRobert https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

ctrl-f or cmd-f for "log"

🍻
